const nodemailer = require("nodemailer");
const { promisify } = require("util");
const path = require("path");
const ejs = require('ejs');

const renderFile = promisify(ejs.renderFile).bind(ejs);

module.exports = (function () {

    const createTransporter = async () => {
        let testAccount = await nodemailer.createTestAccount();

        return nodemailer.createTransport({
            host: "smtp.ethereal.email",
            port: 587,
            secure: false,
            auth: {
                user: testAccount.user,
                pass: testAccount.pass,
            },
        });
    };

    /**
     * 
     * @param {String} name  name of the tempalte which you want to render
     * @param {Object} data  the data object which the template is using intermnally
     * @returns              the rendered EJS template file whcih is palced in templates folder
     *                       with all the dynamic fields which it's using via the data object
     * 
     * @description          Renders the EJS template which is being present in the templates folder
     *                       using the Node.js's path module and EJS template engine to parse the 
     *                       data used by the template, passed as the data argument
     */
    const getEmailTemplate = (name, data) => {
        Object.assign(data, {
            logoUrl: process.env.LOGO,
        });
        const filename = path.join(__dirname, `../templates/${name}.ejs`);
        return renderFile(filename, data);
    };

    /**
     * 
     * @param {Object}
     * @param {String} type             the type of email you want to send, could be html or text
     * @param {Object} data             the data object which will be used int the ejs template
     * @param {string} to               the recipient to whome you want to send the email to
     * @param {String} subject          the subject of the email, that you want to show on the top
     * @param {String} text             optional if the email type is text then only the text is required
     * @param {String} templateName     the name of the template which you want to use to send the email
     * 
     * @description                     This method will send the Email to the reciptent which is mentioned in the
     *                                  to paramater, using the templete which will be rendered using ejs template
     *                                  the mail will be sent via the transport which is generated by the nodmailer
     */
    const sendEmail = async ({ type, data, to, subject, text = "", templateName }) => {
        try {
            const transporter = await createTransporter();

            const options = {
                to,
                from: "'Logger' <no-reply@logger.com>",
                subject
            };

            if (type === "html") {
                options.html = await getEmailTemplate(templateName, data);
            } else if (type === "text" && text) {
                options.text = text;
            }

            return transporter.sendMail(options);

        } catch (err) {
            throw new Error(err);
        }
    };

    return {
        sendEmail
    };

})();
